// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAXEyYb44oswsAGRvOp_ZS2vJyc2FbCXmQ',
    appId: '1:352657115864:web:e52c553a3581d47be4e5ad',
    messagingSenderId: '352657115864',
    projectId: 'kao-type',
    authDomain: 'kao-type.firebaseapp.com',
    storageBucket: 'kao-type.firebasestorage.app',
    measurementId: 'G-J2SHYPVQD7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAdAk1p-7CC_j_3rcFOh9Uaj1XC0WKr7PY',
    appId: '1:352657115864:android:a20c69d609463e18e4e5ad',
    messagingSenderId: '352657115864',
    projectId: 'kao-type',
    storageBucket: 'kao-type.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB5dVb0iIG7oOI8t_77KG_b4a2od6Kv3LY',
    appId: '1:352657115864:ios:73b428dd2f1e12a9e4e5ad',
    messagingSenderId: '352657115864',
    projectId: 'kao-type',
    storageBucket: 'kao-type.firebasestorage.app',
    iosBundleId: 'com.nineconsulting.kaotype',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB5dVb0iIG7oOI8t_77KG_b4a2od6Kv3LY',
    appId: '1:352657115864:ios:289d0581a66372e5e4e5ad',
    messagingSenderId: '352657115864',
    projectId: 'kao-type',
    storageBucket: 'kao-type.firebasestorage.app',
    iosBundleId: 'com.example.facetype',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAXEyYb44oswsAGRvOp_ZS2vJyc2FbCXmQ',
    appId: '1:352657115864:web:7a044d998ebfdbe7e4e5ad',
    messagingSenderId: '352657115864',
    projectId: 'kao-type',
    authDomain: 'kao-type.firebaseapp.com',
    storageBucket: 'kao-type.firebasestorage.app',
    measurementId: 'G-XVM0E6C86D',
  );
}
